class Players {
  // properties
  String name;
  String age;
  String national;
  String height;
  String position;
  String foot;
  String image;
  String profile;

  // constructor
  Players({
    required this.name,
    required this.age,
    required this.national,
    required this.height,
    required this.position,
    required this.foot,
    required this.image,
    required this.profile,
  });
}

var playersList = [
  Players(
    name: 'Marc-André ter Stegen',
    age: '32',
    national: 'Germany',
    height: '1,87 m',
    position: 'Goalkeeper',
    foot: 'Right',
    image: 'assets/images/ter_stegen.png',
    profile:
        'Marc-André ter Stegen (born 30 April 1992) is a German professional footballer who plays as a goalkeeper for La Liga club Barcelona, whom he captains, and the Germany national team. Known for his reflexes, passing, and ball-playing ability,he is considered one of the best goalkeepers in world football.',
  ),
  Players(
    name: 'Wojciech Szczęsny',
    age: '34',
    national: 'Poland',
    height: '1,96 m',
    position: 'Goalkeeper',
    foot: 'Right',
    image: 'assets/images/wojciech_szczesny.png',
    profile:
    'Wojciech Tomasz Szczęsny (born 18 April 1990) is a Polish professional footballer who plays as a goalkeeper for La Liga club Barcelona. After starting his club career at Legia Warsaw, Szczęsny signed for Arsenal in January 2006, where he made his professional debut in 2009. He subsequently went on two consecutive season-long loans to Italian club Roma in 2015, where his performances earned him a move to reigning league champions Juventus in 2017.',
  ),
  Players(
    name: 'Iñaki Peña',
    age: '25',
    national: 'Spain',
    height: '1,84 m',
    position: 'Goalkeeper',
    foot: 'Right',
    image: 'assets/images/inaki_pena.png',
    profile: 'Iñaki Peña Born in Alicante, Valencian Community, Peña started his career at Alicante CF\'s youth setup in 2004, aged just five. In 2012, at the age of 13, he joined FC Barcelona\'s La Masia from Villarreal CF. He was in the team that won the 2017–18 UEFA Youth League, being a starter in the final against Chelsea.',
  ),
  Players(
    name: 'Ander Astralaga',
    age: '20',
    national: 'Spain',
    height: '1,90 m',
    position: 'Goalkeeper',
    foot: 'Left',
    image: 'assets/images/ander_astralaga.png',
    profile: 'Ander Astralaga Born in Berango, Astralaga started his career with the Karabigane local club. In 2014, he then moved to Athletic Bilbao\'s youth academy. In the summer of 2018 Astralaga came to La Masia and joined the U16 team. There he continued to grow and, through the team\'s youth system, he played his first match for Barça Atlètic against Betis Deportivo on 27 March 2022.',
  ),
  Players(
    name: 'Ronald Araujo',
    age: '25',
    national: 'Uruguay',
    height: '1,92 m',
    position: 'Centre-Back',
    foot: 'Right',
    image: 'assets/images/ronald_araujo.png',
    profile: 'Ronald Araujo Born to a Uruguayan father and a Brazilian mother in Rivera, a city near the Brazil border, Araújo joined Rentistas from hometown club Huracán de Rivera. He made his senior debut with the former on 24 September 2016, coming on as a late substitute in a 1–0 Segunda División away win against Tacuarembó.',
  ),
  Players(
    name: 'Andreas Christensen',
    age: '28',
    national: 'Denmark',
    height: '1,87 m',
    position: 'Centre-Back',
    foot: 'Right',
    image: 'assets/images/andreas_christensen.png',
    profile: 'Andreas Bødtker Christensen (born 10 April 1996) is a Danish professional footballer who plays as a centre-back or defensive midfielder for La Liga club Barcelona and the Denmark national team. Christensen began his career at Skjold Birkerød and later joined Brøndby. He joined Chelsea at the age of 15 in February 2012, making his professional debut in October 2014.',
  ),
  Players(
    name: 'Pau Cubarsí',
    age: '17',
    national: 'Spain',
    height: '1,84 m',
    position: 'Centre-Back',
    foot: 'Right',
    image: 'assets/images/pau_cubarsi.png',
    profile: 'Pau Cubarsí Paredes (born 22 January 2007) is a Spanish professional footballer from Catalonia who plays as a centre-back for La Liga club Barcelona and the Spain national team. Pau Cubarsí Paredes is from Bescanó, Girona, Catalonia. Cubarsí speaks Catalan. While playing for Spain at the Olympic Games in 2024, he said that he rarely takes part in interviews because he is not fluent speaking Spanish, having only ever lived in Catalonia and used his native language.',
  ),
  Players(
    name: 'Eric García',
    age: '23',
    national: 'Spain',
    height: '1,82 m',
    position: 'Centre-Back',
    foot: 'Right',
    image: 'assets/images/eric_garcia.png',
    profile: 'Eric García Martret (born 9 January 2001) is a Spanish professional footballer who plays as a centre-back or defensive midfielder for La Liga club Barcelona and the Spain national team. García moved from Barcelona at the age of 17 to Manchester City. He made his Premier League debut on 21 September 2019. In his final season at the club, he won the league and was runner-up in the UEFA Champions League.',
  ),
  Players(
    name: 'Iñigo Martínez',
    age: '33',
    national: 'Spain',
    height: '1,82 m',
    position: 'Centre-Back',
    foot: 'Left',
    image: 'assets/images/inigo_martinez.png',
    profile: 'Iñigo Martínez Berridi (born 17 May 1991) is a Spanish professional footballer who plays as a centre-back for La Liga club Barcelona and the Spain national team. He spent most of his professional career with Real Sociedad, playing 238 matches (17 goals scored) in all competitions after making his debut at the age of 20. In January 2018, he signed with Athletic Bilbao, with whom he won the 2020–21 Supercopa de España as well as reaching two Copa del Rey finals.',
  ),
  Players(
    name: 'Alejandro Balde',
    age: '21',
    national: 'Spain',
    height: '1,75 m',
    position: 'Left-Back',
    foot: 'Left',
    image: 'assets/images/alejandro_balde.png',
    profile: 'Alejandro Balde Martínez (born 18 October 2003) is a Spanish professional footballer who plays as a left-back for La Liga club Barcelona and the Spain national team. Born in Barcelona, Catalonia, to a Bissau-Guinean father and a Dominican mother, Balde joined Barcelona in 2011 at the age of eight after coming up through ranks at Espanyol. In July 2021, he signed a contract renewal with Barcelona until 2024 with a release clause of 500 million euros.',
  ),
  Players(
    name: 'Gerard Martín',
    age: '22',
    national: 'Spain',
    height: '1,86 m',
    position: 'Left-Back',
    foot: 'Left',
    image: 'assets/images/gerard_martin.png',
    profile: 'Gerard Martín Langreo (born 26 February 2002) is a Spanish professional footballer who plays as a left-back for Barcelona Atlètic. Born in Esplugues de Llobregat, Barcelona, Catalonia, Martín moved with his family to Sant Andreu de la Barca at the age of five. In 2023, Martín signed for Spanish side Barcelona Atlètic, where he was described as "one of the key defensive players".',
  ),
  Players(
    name: 'Jules Koundé',
    age: '25',
    national: 'France',
    height: '1,80 m',
    position: 'Left-Back',
    foot: 'Right',
    image: 'assets/images/jules_kounde.png',
    profile: 'Jules Olivier Koundé (born 12 November 1998) is a French professional footballer who plays as a right-back or centre-back for La Liga club Barcelona and the France national team.Jules Olivier Koundé was born on 12 November 1998 in Paris and grew up in Landiras, Gironde. His father is Beninese and Koundé holds citizenship of both Benin and France. His uncle Charles Tokplé is a former footballer who played for the Togo national team.',
  ),
  Players(
    name: 'Héctor Fort',
    age: '18',
    national: 'Spain',
    height: '1,85 m',
    position: 'Right-Back',
    foot: 'Right',
    image: 'assets/images/hector_fort.png',
    profile: 'Héctor Fort García (born 2 August 2006) is a Spanish professional footballer who plays as a right-back for Barcelona B. Born in Barcelona, Catalonia, Fort signed for La Masia from PB Anguera, representing the club\'s Juvenil A side in the 2022–23 season and playing all six matches in their Youth League campaign.',
  ),
  Players(
    name: 'Marc Casadó',
    age: '21',
    national: 'Spain',
    height: '1,72 m',
    position: 'Defensive-Midfield',
    foot: 'Right',
    image: 'assets/images/marc_casado.png',
    profile: 'Marc Casadó Torras (born 14 September 2003) is a Spanish professional footballer from Catalonia who plays as a defensive midfielder for La Liga club Barcelona. Born in Sant Pere de Vilamajor, Barcelona, Catalonia, Casadó is a youth product of Vilamajor, Sant Celoni, Granollers and Damm. He moved to Barcelona\'s youth academy at the age of 13 in 2016.',
  ),
  Players(
    name: 'Marc Bernal',
    age: '17',
    national: 'Spain',
    height: '1,91 m',
    position: 'Defensive-Midfield',
    foot: 'Left',
    image: 'assets/images/marc_bernal.png',
    profile: 'Marc Bernal Casas (born 26 May 2007) is a Spanish professional footballer who plays as a defensive midfielder for Barcelona Atlètic. Born in Berga, Barcelona, Catalonia, Bernal is a youth product of CE Berga and Gimnàstic Manresa, and moved to La Masia at the age of 6 where he worked his way up their youth categories. On 23 June 2023, he signed his first professional contract with Barcelona until 2026.',
  ),
  Players(
    name: 'Gavi',
    age: '20',
    national: 'Spain',
    height: '1,73 m',
    position: 'Central-Midfield',
    foot: 'Right',
    image: 'assets/images/gavi.png',
    profile: 'Pablo Martín Páez Gavira (born 5 August 2004), known as Gavi, is a Spanish professional footballer who plays as a central midfielder for La Liga club Barcelona and the Spain national team. In 2022, Gavi won the Golden Boy award and received the Kopa Trophy, awarded by France Football during the 2022 Ballon d\'Or ceremony. Gavi started his career at La Liara Balompié, a club in his hometown, where he spent two years, between 2010 and 2012.',
  ),
  Players(
    name: 'Pedri',
    age: '21',
    national: 'Spain',
    height: '1,74 m',
    position: 'Central-Midfield',
    foot: 'Right',
    image: 'assets/images/pedri.png',
    profile: 'Pedro González López (born 25 November 2002), more commonly known as Pedri, is a Spanish professional footballer who plays as a central midfielder for La Liga club Barcelona and the Spain national team. Born in Bajamar, Tenerife, Canary Islands, Pedri\'s family moved to Tegueste, a nearby town, when he was 3. Pedri joined UD Tegueste, starting as a centre-back. At 13, Pedri signed for CF Juventud Laguna, where he played until 2018.',
  ),
  Players(
    name: 'Frenkie de Jong',
    age: '27',
    national: 'Netherlands',
    height: '1,81 m',
    position: 'Central-Midfield',
    foot: 'Right',
    image: 'assets/images/frenkie_de_jong.png',
    profile: 'Frenkie de Jong (born 12 May 1997) is a Dutch professional footballer who plays as a central midfielder for La Liga club Barcelona and the Netherlands national team. Considered as one of the best midfielders in the world, de Jong is known for his vision, passing, dribbling, attacking prowess and technique. De Jong began his professional career at Willem II in 2015. He transferred to Ajax for a fee worth €1 a year later. The fee was symbolic and offset by a sell-on clause.',
  ),
  Players(
    name: 'Fermín López',
    age: '21',
    national: 'Spain',
    height: '1,74 m',
    position: 'Central-Midfield',
    foot: 'Right',
    image: 'assets/images/fermin_lopez.png',
    profile: 'Fermín López Marín (born 11 May 2003) is a Spanish professional footballer who plays as a midfielder for La Liga club Barcelona and the Spain national team. Born in El Campillo, Huelva, Andalusia, López began playing football with his local club CD FB El Campillo, and followed that with a stint at Recreativo de Huelva before moving to Real Betis in 2012. In the summer of 2016, he moved to the youth academy of Barcelona.',
  ),
  Players(
    name: 'Dani Olmo',
    age: '26',
    national: 'Spain',
    height: '1,79 m',
    position: 'Attacking-Midfield',
    foot: 'Right',
    image: 'assets/images/dani_olmo.png',
    profile: 'Daniel Olmo Carvajal (born 7 May 1998) is a Spanish professional footballer who plays as an attacking midfielder or left winger for La Liga club Barcelona and the Spain national team. After a period at La Masia, Olmo made his professional debut for Dinamo Zagreb in Croatia in 2015. He made 124 total appearances for the club, scoring 34 goals and winning the league five times and the cup three times.',
  ),
  Players(
    name: 'Pablo Torre',
    age: '21',
    national: 'Spain',
    height: '1,73 m',
    position: 'Attacking-Midfield',
    foot: 'Right',
    image: 'assets/images/pablo_torre.png',
    profile: 'Pablo Torre Carral (born 3 April 2003) is a Spanish professional footballer who plays as an attacking midfielder for La Liga club Barcelona. Born in Soto de la Marina, Cantabria, Torre joined Racing de Santander\'s youth setup in 2015, from CD Marina Sport. On 15 April 2020, while still a youth, he signed a professional contract with the club, until June 2025.',
  ),
  Players(
    name: 'Ansu Fati',
    age: '21',
    national: 'Spain',
    height: '1,78 m',
    position: 'Left-Winger',
    foot: 'Right',
    image: 'assets/images/ansu_fati.png',
    profile: 'Anssumane Fati Vieira (born 31 October 2002) is a professional footballer who plays as a forward or winger for La Liga club Barcelona. Born in Guinea-Bissau, he plays for the Spain national team. Fati was born on 31 October 2002 in Bissau, Guinea-Bissau. He moved to Seville with his family at the age of five, when his older brother Braima signed for Sevilla. His other brother, Miguel Fati, is also a footballer. His older cousin, Ença Fati is also a footballer.',
  ),
  Players(
    name: 'Lamine Yamal',
    age: '17',
    national: 'Spain',
    height: '1,80 m',
    position: 'Right-Winger',
    foot: 'Left',
    image: 'assets/images/lamine_yamal.png',
    profile: 'Lamine Yamal Nasraoui Ebana (born 13 July 2007) is a Spanish professional footballer who plays as a right winger for La Liga club Barcelona and the Spain national team. Known for his pace, dribbling, passing, crossing ability, physicality, defensive capability, and ability to strike powerful long-range shots, He is widely regarded as one of the best young footballers in the world.',
  ),
  Players(
    name: 'Raphinha',
    age: '27',
    national: 'Brazil',
    height: '1,76 m',
    position: 'Right-Winger',
    foot: 'Left',
    image: 'assets/images/raphinha.png',
    profile: 'Raphael Dias Belloli (born 14 December 1996), known as Raphinha, is a Brazilian professional footballer who plays as a winger for La Liga club Barcelona and the Brazil national team. Raphinha began his footballing journey with Avaí, but left for Portuguese side Vitória Guimarães in 2016, where he made his professional début. After impressive performances, he signed for Sporting CP, where he spent a year before signing for French club Rennes.',
  ),
  Players(
    name: 'Ferran Torres',
    age: '24',
    national: 'Spain',
    height: '1,84 m',
    position: 'Right-Winger',
    foot: 'Right',
    image: 'assets/images/ferran_torres.png',
    profile: 'Ferran Torres García (born 29 February 2000) is a Spanish professional footballer who plays as a forward or winger for La Liga club Barcelona and the Spain national team. Torres began his career at Valencia, where he made his senior debut in 2017. He moved to Manchester City in 2020 and won the Premier League and the EFL Cup in the 2020–21 season. He departed for Barcelona in January 2022.',
  ),
  Players(
    name: 'Pau Víctor',
    age: '22',
    national: 'Spain',
    height: '1,84 m',
    position: 'Centre-Forward',
    foot: 'Right',
    image: 'assets/images/pau_victor.png',
    profile: 'Pau Víctor Delgado (born 26 November 2001) is a Spanish professional footballer who plays as a forward or winger for La Liga club Barcelona. Born in Sant Cugat del Vallès, Barcelona, Catalonia, Víctor began his career with hometown side Junior FC nd joined Girona\'s youth setup in 2018, from Sabadell.',
  ),
  Players(
    name: 'Robert Lewandowski',
    age: '36',
    national: 'Poland',
    height: '1,85 m',
    position: 'Centre-Forward',
    foot: 'Right',
    image: 'assets/images/robert_lewandowski.png',
    profile: 'Robert Lewandowski (born 21 August 1988) is a Polish professional footballer who plays as a striker for La Liga club Barcelona and captains the Poland national team. He is regarded as one of the best players of his generation and as one of the best strikers of all time. He is one of the most successful players in Bundesliga and Bayern Munich history. He has scored over 600 senior career goals for club and country.',
  ),
];
